mskcc/smile-label-generator

src/main/java/org/mskcc/cmo/metadb/service/impl/LabelGenMessageHandlingServiceImpl.java

Set requestId for samples extracted from request json

---

pom.xml

Docker build 1.1.0-RC

---

pom.xml
src/main/java/org/mskcc/cmo/metadb/service/CmoLabelGeneratorService.java
src/main/java/org/mskcc/cmo/metadb/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/cmo/metadb/service/impl/LabelGenMessageHandlingServiceImpl.java
src/test/java/org/mskcc/cmo/metadb/PortedLimsRestCmoLabelGenerationTest.java

- Made updates related to the refactoring efforts in `cmo-metadb` 
- Data extracted from request JSONs are now explicitly modeled as IgoSampleManifest objects instead of the models that are persisted in Metadb (SampleMetadata)
--
--
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for more …

Updates to MetaDB model dependency and related changes

---

pom.xml

- cmo-metadb-common: 1.1.9.RELEASE
- cmo-messaging-java: 1.1.8.RELEASE
- cmo-metadb: 1.1.6.RELEASE

Update metadb dependencies

---

pom.xml
src/test/java/org/mskcc/cmo/metadb/PortedLimsRestCmoLabelGenerationTest.java

Update Metadb dependencies to `1.2.0.RELEASE`

1.2.0.RELEASE

---

pom.xml
src/main/java/org/mskcc/cmo/metadb/service/CmoLabelGeneratorService.java
src/main/java/org/mskcc/cmo/metadb/service/MessageHandlingService.java
src/main/java/org/mskcc/cmo/metadb/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/cmo/metadb/service/impl/LabelGenMessageHandlingServiceImpl.java
src/main/resources/application.properties.EXAMPLE
src/test/java/org/mskcc/cmo/metadb/PortedLimsRestCmoLabelGenerationTest.java

1. Added message handler for CMO_SAMPLE_LABEL_UPDATE topic
2. Adds logic for identifying a sample matching an igo id of an existing sample
If match found then metadata fields used for generating the cmo label are compared
against each other to determine whether the incoming sample metadat contains an update
that warrants generating a new label
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting …

Added message handler for CMO_SAMPLE_LABEL_UPDATE topic

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/main/java/org/mskcc/smile/service/util/RequestStatusLogger.java
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java

- a
- b 
---
**Tasks**
---
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting …

Improve logging for label generation request status failures

---

src/main/java/org/mskcc/smile/service/MessageHandlingService.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/main/resources/application.properties.EXAMPLE

Label generator service now supports promoted requests.
- refactored a bit to consolidate duplicate code and to reuse message handler logic
- added enum to direct messages to the appropriate destination topic based on which
subject they were received on
- updated example properties
---
Please …

Promoted Request Support

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

-  Conditionally use existing sample label if exception thrown during check for updates
---
If no unit tests were updated or added, then please explain why: existing unit tests to handle case
Please describe how the workflow …

Conditionally use existing sample label

---

pom.xml

Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>

new smile-server docker image

---

pom.xml

commons version to 1.3.8.RELEASE and smile-server version to 1.3.11.RELEASE

Update commons and smiler-server versions

---

src/main/java/org/mskcc/smile/service/CmoLabelGeneratorService.java
src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java

Signed-off-by: Divya Madala <71040191+divyamadala30@users.noreply.github.com>
- Adds status node to new or updated sample jsons
---
Updates were made to the mocked …

draft status commit

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

- igoSampleManifest throws an error when sample json has field status
- So changed the mapping to SampleMetadata to ignore unknown fields
---
Updates were made to the …

get patient samples by SampleMetadata

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

- Status mapping error resolved
---
Updates were made to the mocked incoming request data and/or mocked published request data:
Please describe how the …

status mapping error resolved

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java

- If sampleType cannot be resolved, the default value will Unknown Tumor from CmoSampleClass
Updates were made to the mocked incoming request data and/or mocked published …

default sampleType to unknown tumor

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java

Reverts mskcc/smile-label-generator#53

Revert "default sampleType to unknown tumor"

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/test/java/org/mskcc/smile/PortedLimsRestCmoLabelGenerationTest.java

- Null labels are now accepted
Updates were made to the mocked incoming request data and/or mocked published request data:
Please describe how the …

accept existing null labels

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

The label generator was dropping `sampleStatus` for new incoming samples.

Sample status bug fix

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java

Allow underscores in CMO cell line sample labels

Allow underscores in cmo cell line sample labels

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

- Missing cmoSampleName field in existing samples list
Updates were made to the mocked incoming request data and/or mocked published request data:
Please …

sample counter fix

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/test/resources/data/incoming_requests/mocked_request7_samples_missing_pids.json
src/test/resources/data/mocked_request_data_details.txt
src/test/resources/data/other_mocked_data/mocked_validated_request7_samples_missing_pids.json

These changes add an extra precaution against accidentally sending a req-reply to the `smile-server` with an empty CMO patient ID. This should already be getting caught by the `request-filter` but is being added here as well just in case. 
--- …

Catch missing CMO patient IDs

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java

- Skips samples that do not have a defined CMO sample label/name

Handle NPE in getNextSampleIncrement()

---

pom.xml

Updates to SMILE server model package and SMILE commons and messaging lib dependencies.

update smile commons and smile messaging lib dependencies

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java

Updated nucleic acid abbreviation rules to include new expected value for resolving abbreviations to RNA (r)

Patch for Recipe db updates in IGO

---

src/main/java/org/mskcc/smile/service/CmoLabelGeneratorService.java
src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

Added additional logging for datadog.

Additional logging for datadaog

---

.circleci/config.yml
Dockerfile
jitpack.yml
pom.xml

Update to java21

---

pom.xml

Update smile-server version

---

.circleci/config.yml
Dockerfile
jitpack.yml
pom.xml
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/RequestReplyHandlingServiceImpl.java
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java
src/test/java/org/mskcc/smile/LabelGeneratorTestApp.java
src/test/java/org/mskcc/smile/PortedLimsRestCmoLabelGenerationTest.java

General updates:
- Support java21
- Spring framework and spring boot updates
- Updated test layer to junit-jupiter
- Updated circleci config

Update SMILE dependencies to 2.0.0.RELEASE

---

pom.xml

Update smile-server to 2.0.2.RELEASE

Update smile-server to 2.0.2.RELEASE

---

pom.xml
src/main/java/org/mskcc/smile/service/CmoLabelGeneratorService.java
src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/RequestReplyHandlingServiceImpl.java
src/main/resources/application.properties.EXAMPLE
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java
src/test/java/org/mskcc/smile/PortedLimsRestCmoLabelGenerationTest.java

TODO:
- a
- b 
---
**Tasks**
---
Please follow these checklists to help prevent any unexpected issues from being introduced by the changes in this pull request. If an item does not apply then indicate so by surrounding the line item with `~~` to strikethrough the text. See [basic writing and formatting syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-gith …

Init commit - alt id support

---

pom.xml
src/main/java/org/mskcc/smile/service/CmoLabelGeneratorService.java
src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/RequestReplyHandlingServiceImpl.java
src/main/resources/application.properties.EXAMPLE
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java
src/test/java/org/mskcc/smile/PortedLimsRestCmoLabelGenerationTest.java
src/test/resources/data/incoming_requests/mocked_request1_complete_tumor_normal_updated_libraries.json
src/test/resources/data/incoming_requests/mocked_request1_sample_missing_fastqs.json
src/test/resources/data/incoming_requests/mocked_request1_updated_complete_tumor_normal.json
src/test/resources/data/incoming_requests/mocked_request1a_sample_type_abbreviation.json
src/test/resources/data/incoming_requests/mocked_request1b_nucleic_acid_abbreviation.json
src/test/resources/data/incoming_requests/mocked_request1c_missing_all_samples.json
src/test/resources/data/incoming_requests/mocked_request1d_missing_few_samples.json
src/test/resources/data/incoming_requests/mocked_request1e_null_string_baitset.json
src/test/resources/data/incoming_requests/mocked_request2a_one_empty_sample_metadata.json
src/test/resources/data/incoming_requests/mocked_request2a_one_normal.json
src/test/resources/data/incoming_requests/mocked_request2b_missing_one_normal.json
src/test/resources/data/incoming_requests/mocked_request3_pooled_normals.json
src/test/resources/data/incoming_requests/mocked_request4_null_or_empty_values.json
src/test/resources/data/incoming_requests/mocked_request5_pt_multi_samples.json
src/test/resources/data/incoming_requests/mocked_request6_cmopt_after_swap.json
src/test/resources/data/incoming_requests/mocked_request6_cmopt_swap.json
src/test/resources/data/incoming_requests/mocked_request8_duplicate_cmo_labels.json
src/test/resources/data/mocked_request_data_details.txt
src/test/resources/data/published_requests/outgoing_mocked_request8_duplicate_cmo_labels.json

- Uses samples matching a given ALT ID when assigning sample counters in CMO labels
- Updated mock data and added unit tests
- Updated smile-server version
---
If no unit …

Use ALT IDs when assigning sample counter to CMO labels

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java

Fix nucleic acid counter to resolve based on next consecutive counter

---

src/main/java/org/mskcc/smile/service/impl/LabelGenMessageHandlingServiceImpl.java

Handle empty or null alt id, cmo label

---

.github/PULL_REQUEST_TEMPLATE.md
src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java

- Sample type abbreviations R, M, and P now resolve to T 
- Adjacent Tissue now resolves to sample type abbreviation 'A'
---
```
```
Please describe how the workflow and …

Updates to resolved sample type abbreviation values

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java
src/test/java/org/mskcc/smile/CmoLabelGeneratorServiceTest.java

- Captures more samples that full under the umbrella of cfDNA sample types
- Added tests to ensure the expected sample type abbreviations are generated even with the updated logic
--- …

Update label generator logic for cfDNA samples

---

src/main/resources/application.properties.EXAMPLE
src/test/java/org/mskcc/smile/config/TestConfiguration.java

Nothing and no one uses the failed published messages file system logger. Removing.

Remove unused file system logger file.

---

src/main/java/org/mskcc/smile/service/impl/CmoLabelGeneratorServiceImpl.java

ALT ID bug fix
